## 2.4

### 2.4.1

In [1]:
a=[1,2]

2-element Vector{Int64}:
 1
 2

In [2]:
A =[1 2
    3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [3]:
b=A*a

2-element Vector{Int64}:
  5
 11

In [4]:
A =[0 -im
    im 0]

2×2 Matrix{Complex{Int64}}:
 0+0im  0-1im
 0+1im  0+0im

In [5]:
a=1/sqrt(2)*[1,1]

2-element Vector{Float64}:
 0.7071067811865475
 0.7071067811865475

In [6]:
b=1/sqrt(2)*[1,-1]

2-element Vector{Float64}:
  0.7071067811865475
 -0.7071067811865475

In [7]:
c=b'*A*a

0.0 - 0.9999999999999998im

### 2.4.2

In [8]:
a=[1,2,3,4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [9]:
B =[1 2 3 4
    5 6 7 8]

2×4 Matrix{Int64}:
 1  2  3  4
 5  6  7  8

In [10]:
B=[1 2 3 4;5 6 7 8]

2×4 Matrix{Int64}:
 1  2  3  4
 5  6  7  8

In [11]:
a =[1
    2
    3
    4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [12]:
a=[1;2;3;4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [13]:
b=[1 2 3 4]

1×4 Matrix{Int64}:
 1  2  3  4

In [14]:
b*a

1-element Vector{Int64}:
 30

In [15]:
a*b

4×4 Matrix{Int64}:
 1  2   3   4
 2  4   6   8
 3  6   9  12
 4  8  12  16

In [16]:
B=zeros(3,4)

3×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [17]:
B[1,2]=3

3

In [18]:
function make_matrix(n)
    H=zeros(n,n)
    for i=1:n
        j=i+1
        j+=ifelse(j>n,-n,0)
        H[i,j]=-1
        j=j-1
        j+=ifelse(j<1,n,0)
        H[i,j]=-1
        H[i,i]=2
    end
    return H
end

make_matrix (generic function with 1 method)

In [19]:
make_matrix(10)

10×10 Matrix{Float64}:
  2.0  -1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   2.0  -1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   2.0  -1.0   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   2.0  -1.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   2.0  -1.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   2.0  -1.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0   2.0  -1.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0  -1.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0  -1.0
 -1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0

In [20]:
A =[1 2 3
    4 5 6
    7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [21]:
A[1:2,1:2]

2×2 Matrix{Int64}:
 1  2
 4  5

In [22]:
A[2:3,2:3]

2×2 Matrix{Int64}:
 5  6
 8  9

In [23]:
A[[1,3],[1,3]]

2×2 Matrix{Int64}:
 1  3
 7  9

In [24]:
A[:,1]

3-element Vector{Int64}:
 1
 4
 7

In [25]:
A[1:3,1]

3-element Vector{Int64}:
 1
 4
 7

In [26]:
A[begin:end,1]

3-element Vector{Int64}:
 1
 4
 7

In [27]:
size(A)

(3, 3)

In [28]:
length(A)

9

### 2.4.3

In [29]:
using LinearAlgebra

In [30]:
a⋅b

30

In [31]:
dot(a,b)

30

In [32]:
a=[3,2im]

2-element Vector{Complex{Int64}}:
 3 + 0im
 0 + 2im

In [33]:
a⋅a

13 + 0im

In [34]:
a'⋅a

5 + 0im

In [35]:
a'*a

13 + 0im

In [36]:
A=rand(ComplexF64,3,3)

3×3 Matrix{ComplexF64}:
 0.443492+0.545607im  0.982036+0.352317im  0.315787+0.676811im
 0.151224+0.781473im  0.412932+0.543914im    0.7669+0.37215im
 0.401433+0.547186im  0.740783+0.388958im  0.394935+0.146178im

In [37]:
A'

3×3 adjoint(::Matrix{ComplexF64}) with eltype ComplexF64:
 0.443492-0.545607im  0.151224-0.781473im  0.401433-0.547186im
 0.982036-0.352317im  0.412932-0.543914im  0.740783-0.388958im
 0.315787-0.676811im    0.7669-0.37215im   0.394935-0.146178im

In [38]:
transpose(A)

3×3 transpose(::Matrix{ComplexF64}) with eltype ComplexF64:
 0.443492+0.545607im  0.151224+0.781473im  0.401433+0.547186im
 0.982036+0.352317im  0.412932+0.543914im  0.740783+0.388958im
 0.315787+0.676811im    0.7669+0.37215im   0.394935+0.146178im

In [39]:
a=rand(3)

3-element Vector{Float64}:
 0.26321033631064195
 0.34518957325374755
 0.545668056643113

In [40]:
b

1×4 Matrix{Int64}:
 1  2  3  4

In [41]:
d=rand(3)

3-element Vector{Float64}:
 0.3852020499165094
 0.3597551019490871
 0.9353163837517536

In [42]:
cross(a,d)

3-element Vector{Float64}:
  0.12655459601650285
 -0.035992485931267415
 -0.038276469853660136

In [43]:
x=A\b

LoadError: DimensionMismatch: arguments must have the same number of rows

In [44]:
A

3×3 Matrix{ComplexF64}:
 0.443492+0.545607im  0.982036+0.352317im  0.315787+0.676811im
 0.151224+0.781473im  0.412932+0.543914im    0.7669+0.37215im
 0.401433+0.547186im  0.740783+0.388958im  0.394935+0.146178im

In [45]:
b

1×4 Matrix{Int64}:
 1  2  3  4

In [46]:
b =[1
    2
    3
    4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [47]:
x=A\b

LoadError: DimensionMismatch: arguments must have the same number of rows

In [48]:
b =[1
    2
    3]

3-element Vector{Int64}:
 1
 2
 3

In [49]:
x=A\b

3-element Vector{ComplexF64}:
 -24.304300038606804 - 11.491113672620548im
   16.68299842703791 + 10.167586174087598im
 -1.1018830232892856 + 10.259898634259065im

In [50]:
A*x-b

3-element Vector{ComplexF64}:
 -8.881784197001252e-16 + 8.881784197001252e-16im
  3.552713678800501e-15 + 2.6645352591003757e-15im
 -4.440892098500626e-16 - 1.3322676295501878e-15im

In [51]:
e,v=eigen(A)

Eigen{ComplexF64, ComplexF64, Matrix{ComplexF64}, Vector{ComplexF64}}
values:
3-element Vector{ComplexF64}:
 -0.28844756357920354 - 0.20301624278447403im
 0.024452221643270954 - 0.08367828618128413im
   1.5153541861302862 + 1.5223937342193223im
vectors:
3×3 Matrix{ComplexF64}:
 -0.546662+0.423971im   0.794697+0.0im       0.648517+0.0im
  0.693622+0.0im       -0.517303-0.151181im  0.554275+0.109624im
 -0.155905-0.126458im   -0.13659-0.243599im  0.508294-0.0427202im

In [52]:
e

3-element Vector{ComplexF64}:
 -0.28844756357920354 - 0.20301624278447403im
 0.024452221643270954 - 0.08367828618128413im
   1.5153541861302862 + 1.5223937342193223im

In [53]:
v

3×3 Matrix{ComplexF64}:
 -0.546662+0.423971im   0.794697+0.0im       0.648517+0.0im
  0.693622+0.0im       -0.517303-0.151181im  0.554275+0.109624im
 -0.155905-0.126458im   -0.13659-0.243599im  0.508294-0.0427202im

In [54]:
A*v[:,1]-e[1]*v[:,1]

3-element Vector{ComplexF64}:
 1.1102230246251565e-16 + 2.914335439641036e-16im
  2.498001805406602e-16 + 1.3877787807814457e-16im
 2.1163626406917047e-16 + 9.71445146547012e-17im

In [55]:
B=A'*A

3×3 Matrix{ComplexF64}:
  1.5885+0.0im       1.62546-0.869204im  1.15465-0.572592im
 1.62546+0.869204im  2.25492+0.0im       1.41708+0.244614im
 1.15465+0.572592im  1.41708-0.244614im  1.46177+0.0im

In [56]:
e,v=eigen(B)

Eigen{ComplexF64, Float64, Matrix{ComplexF64}, Vector{Float64}}
values:
3-element Vector{Float64}:
 0.002115540381500206
 0.42255309740511277
 4.8805264792342955
vectors:
3×3 Matrix{ComplexF64}:
 -0.141689+0.758232im  -0.260349-0.139891im  -0.519388+0.218845im
  0.210417-0.52424im   -0.469789+0.138088im  -0.659066-0.0822171im
  0.293096-0.0im        0.820292+0.0im       -0.491137-0.0im

In [57]:
tr(log(B))

-5.434632066205823 + 0.0im

In [58]:
log(B) |> tr

-5.434632066205823 + 0.0im

In [59]:
logdet(B)

-5.434632066205771 + 2.3342439092743916e-14im

### 2.4.4

In [60]:
B=zeros(3,3)

3×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [61]:
B[1,2]=4+2im

LoadError: InexactError: Float64(4 + 2im)

In [62]:
B=zeros(ComplexF64,3,3)

3×3 Matrix{ComplexF64}:
 0.0+0.0im  0.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+0.0im

In [63]:
B[1,2]=4+2im

4 + 2im

B =[2 1.2
    3 4.1]

In [65]:
B =[2 1.2
    3 4.1+im]

2×2 Matrix{ComplexF64}:
 2.0+0.0im  1.2+0.0im
 3.0+0.0im  4.1+1.0im

In [66]:
B=ones(3,3)

3×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [67]:
B=rand(3,3)

3×3 Matrix{Float64}:
 0.0987608  0.235827  0.466026
 0.993944   0.326229  0.427058
 0.56801    0.302713  0.138785

In [68]:
B=randn(3,3)

3×3 Matrix{Float64}:
 -1.88323    1.47938    1.15944
  0.083124   0.773149  -0.0310245
  0.408274  -2.11249   -1.933

In [69]:
B=Matrix{Float64}(undef,2,3)

2×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [70]:
B

2×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0

### 2.4.5

In [72]:
a=zeros(4,4,4)

4×4×4 Array{Float64, 3}:
[:, :, 1] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

[:, :, 3] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

[:, :, 4] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [73]:
C=Array{Float64,3}(undef,2,2,2)

2×2×2 Array{Float64, 3}:
[:, :, 1] =
 4.24399e-314  4.24399e-314
 4.24399e-314  6.36599e-314

[:, :, 2] =
 1.4854e-313  1.6976e-313
 1.6976e-313  4.0e-323

In [74]:
diagm(1=>[1,2])

3×3 Matrix{Int64}:
 0  1  0
 0  0  2
 0  0  0

In [75]:
diagm(1=>[1,2,3,4,5])

6×6 Matrix{Int64}:
 0  1  0  0  0  0
 0  0  2  0  0  0
 0  0  0  3  0  0
 0  0  0  0  4  0
 0  0  0  0  0  5
 0  0  0  0  0  0

### 2.4.6

In [76]:
a =[1 2
    3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [77]:
a[:]

4-element Vector{Int64}:
 1
 3
 2
 4

In [78]:
reshape(a,(4,1))

4×1 Matrix{Int64}:
 1
 3
 2
 4

In [79]:
length(a)

4

In [81]:
reshape(a,(1,4))

1×4 Matrix{Int64}:
 1  3  2  4

In [82]:
b=rand(2,2,2)

2×2×2 Array{Float64, 3}:
[:, :, 1] =
 0.552497  0.831546
 0.242373  0.355274

[:, :, 2] =
 0.214788  0.192183
 0.965387  0.880514

In [83]:
reshape(b,(4,2))

4×2 Matrix{Float64}:
 0.552497  0.214788
 0.242373  0.965387
 0.831546  0.192183
 0.355274  0.880514

### 2.4.7

In [84]:
a=3

3

In [85]:
typeof(a)

Int64

In [86]:
b=rand(3,3)

3×3 Matrix{Float64}:
 0.543411  0.716324  0.865783
 0.728782  0.581589  0.97822
 0.231394  0.471532  0.263381

In [87]:
typeof(b)

Matrix{Float64} (alias for Array{Float64, 2})

In [88]:
B=Matrix{Matrix{Float64}}(undef,2,3)

2×3 Matrix{Matrix{Float64}}:
 #undef  #undef  #undef
 #undef  #undef  #undef

In [89]:
B[1,1]=rand(2,3)

2×3 Matrix{Float64}:
 0.043909  0.207442  0.903843
 0.635265  0.308593  0.134249

In [90]:
B[1,2]=rand(1,1)

1×1 Matrix{Float64}:
 0.828924104277979

In [91]:
B

2×3 Matrix{Matrix{Float64}}:
    [0.043909 0.207442 0.903843; 0.635265 0.308593 0.134249]  …     [0.828924;;]  #undef
 #undef                                                          #undef           #undef

In [92]:
B[1,3]

LoadError: UndefRefError: access to undefined reference

In [93]:
C=Array{Array{Float64,2},3}(undef,2,2,2)

2×2×2 Array{Matrix{Float64}, 3}:
[:, :, 1] =
 #undef  #undef
 #undef  #undef

[:, :, 2] =
 #undef  #undef
 #undef  #undef

### 2.4.8

In [94]:
function y(x,W1,W2,b1,b2)
    xp=W1*x+b1
    m=length(xp)
    f(x)=tanh(x)
    for i=1:m
        xp[i]=f(xp[i])
    end
    wxp=W2*xp
    return wxp[1]+b2
end

y (generic function with 1 method)

In [95]:
function y2(x,W1,W2,b1,b2)
    f(x)=tanh(x)
    return W2*f.(W1*x+b1).+b2
end

y2 (generic function with 1 method)

In [96]:
A =[im*pi 1
    1 im*pi]

2×2 Matrix{ComplexF64}:
 0.0+3.14159im  1.0+0.0im
 1.0+0.0im      0.0+3.14159im

In [97]:
exp(A)

2×2 Matrix{ComplexF64}:
 -1.54308+1.49186e-16im   -1.1752+1.07553e-16im
  -1.1752+1.07553e-16im  -1.54308+1.35308e-16im

In [98]:
exp.(A)

2×2 Matrix{ComplexF64}:
    -1.0+1.22465e-16im  2.71828+0.0im
 2.71828+0.0im             -1.0+1.22465e-16im

In [99]:
f(x)=cos(x)+exp(3x)

f (generic function with 1 method)

In [100]:
f.(A)

2×2 Matrix{ComplexF64}:
  10.592+3.67394e-16im  20.6258+0.0im
 20.6258+0.0im           10.592+3.67394e-16im

### 2.4.9

In [101]:
A=[]

Any[]

In [102]:
A=Float64[]

Float64[]

In [103]:
A=[]

Any[]

In [104]:
push!(A,2)

1-element Vector{Any}:
 2

In [105]:
push!(A,[1,2])

2-element Vector{Any}:
 2
  [1, 2]

In [106]:
push!(A,"test")

3-element Vector{Any}:
 2
  [1, 2]
  "test"

In [107]:
A=Float64[]

Float64[]

In [108]:
push!(A,2)

1-element Vector{Float64}:
 2.0

In [109]:
push!(A,[1,2])

LoadError: MethodError: Cannot `convert` an object of type Vector{Int64} to an object of type Float64
Closest candidates are:
  convert(::Type{T}, ::T) where T<:Number at number.jl:6
  convert(::Type{T}, ::Number) where T<:Number at number.jl:7
  convert(::Type{T}, ::Base.TwicePrecision) where T<:Number at twiceprecision.jl:273
  ...

In [110]:
A=[]

Any[]

In [111]:
push!(A,2,3,4)

3-element Vector{Any}:
 2
 3
 4

In [112]:
A=Float64[]

Float64[]

In [113]:
append!(A,[2,3,4])

3-element Vector{Float64}:
 2.0
 3.0
 4.0

In [114]:
A

3-element Vector{Float64}:
 2.0
 3.0
 4.0

In [115]:
A=[1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [116]:
B=[4,5,6]

3-element Vector{Int64}:
 4
 5
 6

In [117]:
append!(A,B)

6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6

In [118]:
A=[1,2]

2-element Vector{Int64}:
 1
 2

In [119]:
append!(A,[3,4],[5,6])

6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6

In [120]:
A=[10,20,30]

3-element Vector{Int64}:
 10
 20
 30

In [121]:
deleteat!(A,2)

2-element Vector{Int64}:
 10
 30

In [122]:
A=[10,20,30,40]

4-element Vector{Int64}:
 10
 20
 30
 40

In [123]:
delete!(A,[1,2])

LoadError: MethodError: no method matching delete!(::Vector{Int64}, ::Vector{Int64})
Closest candidates are:
  delete!(::IdDict{K}, ::Any) where K at iddict.jl:130
  delete!(::Base.IdSet, ::Any) at idset.jl:24
  delete!(::Dict, ::Any) at dict.jl:678
  ...

In [124]:
deleteat!(A,[1,2])

2-element Vector{Int64}:
 30
 40

In [125]:
B=[10,20,30,40]

4-element Vector{Int64}:
 10
 20
 30
 40

In [126]:
deleteat!(B,3:4)

2-element Vector{Int64}:
 10
 20