## 2.4

### 2.4.1

In [1]:
a=[1,2]

2-element Vector{Int64}:
 1
 2

In [2]:
A =[1 2
    3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [3]:
b=A*a

2-element Vector{Int64}:
  5
 11

In [4]:
A =[0 -im
    im 0]

2×2 Matrix{Complex{Int64}}:
 0+0im  0-1im
 0+1im  0+0im

In [5]:
a=1/sqrt(2)*[1,1]

2-element Vector{Float64}:
 0.7071067811865475
 0.7071067811865475

In [6]:
b=1/sqrt(2)*[1,-1]

2-element Vector{Float64}:
  0.7071067811865475
 -0.7071067811865475

In [7]:
c=b'*A*a

0.0 - 0.9999999999999998im

### 2.4.2

In [8]:
a=[1,2,3,4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [9]:
B =[1 2 3 4
    5 6 7 8]

2×4 Matrix{Int64}:
 1  2  3  4
 5  6  7  8

In [10]:
B=[1 2 3 4;5 6 7 8]

2×4 Matrix{Int64}:
 1  2  3  4
 5  6  7  8

In [11]:
a =[1
    2
    3
    4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [12]:
a=[1;2;3;4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [13]:
b=[1 2 3 4]

1×4 Matrix{Int64}:
 1  2  3  4

In [14]:
b*a

1-element Vector{Int64}:
 30

In [15]:
a*b

4×4 Matrix{Int64}:
 1  2   3   4
 2  4   6   8
 3  6   9  12
 4  8  12  16

In [16]:
B=zeros(3,4)

3×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [17]:
B[1,2]=3

3

In [18]:
function make_matrix(n)
    H=zeros(n,n)
    for i=1:n
        j=i+1
        j+=ifelse(j>n,-n,0)
        H[i,j]=-1
        j=j-1
        j+=ifelse(j<1,n,0)
        H[i,j]=-1
        H[i,i]=2
    end
    return H
end

make_matrix (generic function with 1 method)

In [19]:
make_matrix(10)

10×10 Matrix{Float64}:
  2.0  -1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   2.0  -1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   2.0  -1.0   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   2.0  -1.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   2.0  -1.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   2.0  -1.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0   2.0  -1.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0  -1.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0  -1.0
 -1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0

In [20]:
A =[1 2 3
    4 5 6
    7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [21]:
A[1:2,1:2]

2×2 Matrix{Int64}:
 1  2
 4  5

In [22]:
A[2:3,2:3]

2×2 Matrix{Int64}:
 5  6
 8  9

In [23]:
A[[1,3],[1,3]]

2×2 Matrix{Int64}:
 1  3
 7  9

In [24]:
A[:,1]

3-element Vector{Int64}:
 1
 4
 7

In [25]:
A[1:3,1]

3-element Vector{Int64}:
 1
 4
 7

In [26]:
A[begin:end,1]

3-element Vector{Int64}:
 1
 4
 7

In [27]:
size(A)

(3, 3)

In [28]:
length(A)

9

### 2.4.3

In [29]:
using LinearAlgebra

In [30]:
a⋅b

30

In [31]:
dot(a,b)

30

In [32]:
a=[3,2im]

2-element Vector{Complex{Int64}}:
 3 + 0im
 0 + 2im

In [33]:
a⋅a

13 + 0im

In [34]:
a'⋅a

5 + 0im

In [35]:
a'*a

13 + 0im

In [36]:
A=rand(ComplexF64,3,3)

3×3 Matrix{ComplexF64}:
 0.443492+0.545607im  0.982036+0.352317im  0.315787+0.676811im
 0.151224+0.781473im  0.412932+0.543914im    0.7669+0.37215im
 0.401433+0.547186im  0.740783+0.388958im  0.394935+0.146178im

In [37]:
A'

3×3 adjoint(::Matrix{ComplexF64}) with eltype ComplexF64:
 0.443492-0.545607im  0.151224-0.781473im  0.401433-0.547186im
 0.982036-0.352317im  0.412932-0.543914im  0.740783-0.388958im
 0.315787-0.676811im    0.7669-0.37215im   0.394935-0.146178im